Repository lospentiumsupc/waw-frontend-vue, pull requests merged in 2022-11, with the labels that each got.

#13 feat: added timeline in job offers admin component
  src/jobs/pages/job-offers-display.component.vue
Labels: enhancement

#16 fix: use incorrect prop for offer status
  src/jobs/pages/job-offers-admin.component.vue
Labels: bug

#17 chore: v0.6.0
  src/jobs/pages/job-offers-admin.component.vue
  src/jobs/pages/job-offers-display.component.vue
Labels: chore
