Repository lospentiumsupc/waw-frontend-vue, pull requests merged in 2022-10, with the labels that each got.

#11 chore(security): updated dependencies
  package-lock.json
Labels: chore, scope: deps

#10 fix: PrimeVue and Tailwind CSS conflicts
  index.html
  package-lock.json
  package.json
  postcss.config.js
Labels: bug

#14 feat(employees): Add profile rating
  src/home/pages/home-profile.component.vue
Labels: enhancement, good first issue

#15 release: v0.5.0
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.vue
  src/core/components/base-header.vue
  src/employers/pages/companies-admin.component.vue
  src/home/pages/home-profile.component.vue
  src/jobs/pages/job-offers-display.component.vue
Labels: enhancement
